### ISSUE TITLE
FindMEs clarification

### ISSUE THREAD

**Issue by feanaros** [smorabit/scWGCNA#103]
Thanks for the wonderful package!
 I need clarification: Why the ME matrix contains cells x modules? I was expecting a Gene x Module matrix, not  a Cell x Module, and also, what are the values ​​inside the matrix? The first PC1 of PCA for each module, should be correct? Finally, when I use the FindMEs() function, why does it call the MEs matrix? this passage is not clear to me, I have always had the conviction that the modules eigengenes are built starting from the genes and not from the cell matrix. Thanks again, john

**Comment by smorabit** [comment]
Hi,

The function `GetMEs` retrieves the module eigengene matrix. Module eigengenes are basically a summary of a module's gene expression, so you get a value for each module in each cell. In the original WGCNA, the equivalent would be a table with values for each module in each sample. You might be looking for the module-gene assignment table which can be retrieved from the Seurat object using `GetModules`. 

> I have always had the conviction that the modules eigengenes are built starting from the genes and not from the cell matrix

We basically take the full genes x cells expression matrix, and subset to just contain the genes assigned to one module. Then we run PCA, so that gives us a cells x PCs matrix. Then we take the top PC, and that is the eigengene for that module. Repeat the process for all the modules, and you then end up with a modules x cells matrix. Hope that helps. If you want to learn more you can check out the methods section of the [hdWGCNA manuscript](https://www.biorxiv.org/content/10.1101/2022.09.22.509094v1).

**Comment by yamihn** [comment]
Hi, thank you for the explanation. I read the manuscript in the we, so module eigengenes concept Is clear to me. But Sorry if ask It again, Just to understand, when I create ME I have the Matrix with cell barcodes  in the row and the value for each cell correspond to First principal component for the module in the corresponding column?

But when U Say:
"Then we run PCA, so that gives us a genes x PCs matrix. Then we take the top PC, and that is the eigengene for that module. Repeat the process for all the modules, and you then end up with a modules x cells matrix"
  Where the genes of the Matrix are now? 
Sorry again for the bothering questions. I was not able to find It in the manuscript

**Comment by feanaros** [comment]
Hi, thank you for the explanation. I read the manuscript in the we, so module eigengenes concept Is clear to me. But Sorry if ask It again, Just to understand, when I create ME I have the Matrix with cell barcodes in the row and the value for each cell correspond to First principal component for the module in the corresponding column?

But when U Say:
"Then we run PCA, so that gives us a genes x PCs matrix. Then we take the top PC, and that is the eigengene for that module. Repeat the process for all the modules, and you then end up with a modules x cells matrix"
Where the genes of the Matrix are now?
Sorry again for the bothering questions. I was not able to find It in the manuscript

**Comment by smorabit** [comment]
>  when I create ME I have the Matrix with cell barcodes in the row and the value for each cell correspond to First principal component for the module in the corresponding column

Yes

> Then we run PCA, so that gives us a genes x PCs matrix

Sorry for the confusion I meant to say cells x PCs matrix.
