### ISSUE TITLE
how to get more modules? 

### ISSUE THREAD

**Issue by ameisesophie** [smorabit/scWGCNA#123]
I utilized metabolome data for the analysis.

dim(seurat_obj@assays$RNA@data)
[1] 744 3787

The optimal power is 8, which resulted in the identification of 3 modules. If I aim to obtain more modules, implying fewer features per module, which parameters can be adjusted?
With the WGCNA package, the parameters [deepSplit] and [minClusterSize] can be modified to control the number of modules and the number of features within each module.

**Comment by ameisesophie** [comment]
> I utilized metabolome data for the analysis.
> 
> dim(seurat_obj@assays$RNA@data) [1] 744 3787
> 
> The optimal power is 8, which resulted in the identification of 3 modules. If I aim to obtain more modules, implying fewer features per module, which parameters can be adjusted? With the WGCNA package, the parameters [deepSplit] and [minClusterSize] can be modified to control the number of modules and the number of features within each module.
---------------  

The function "ConstructNetwork()" can achieve this.

**Comment by smorabit** [comment]
Hi,

In order to change the number of modules that you detect, you can change many of the parameters in the `ConstructNetwork` function, as you can see [here in the function documentation](https://smorabit.github.io/hdWGCNA/reference/ConstructNetwork.html), including the deepSplit and minModuleSize parameters as you mentioned. All of the same parameters from [`blockwiseConsensusModules`](https://www.rdocumentation.org/packages/WGCNA/versions/1.68/topics/blockwiseConsensusModules) should work but I haven't tested them all. As a word of advice, plotting the dendroram with the `PlotDendrogram` you should be able to see by eye some of the major patterns. For example, if you only really see 3 branches in the dendrogram, you are likely to only get 3 modules no matter how much you tweak the parameters. Further, the number of modules changes with the input that you give such as your features and your metacell parameters.

**Comment by smorabit** [comment]
Closing this issue as completed but feel free to re-open if there is any new information.
