### ISSUE TITLE
Question about k parameter in MetacellsByGroups()

### ISSUE THREAD

**Issue by emparbaltasar** [smorabit/scWGCNA#145]
Hi,

Thank you for developing this package! 
I have a question regarding the choice of k parameter in MetacellsByGroups(): Do you have any guidelines on how to choose the optimal k? Should we, for example, aim for a specific sparsity?

Thanks a lot!

**Comment by smorabit** [comment]
Hi, we don't have a procedure for chosing an "optimal" value for K. You should think of it like there is a range of K values that are suitable rather than one magic number. You want to reduce the sparsity of your data while retaining the cellular heterogeneity. In general I would recommend values between 25 and 50. You can try your analysis with different values and see how it changes the results.
