### ISSUE TITLE
Why did you plot module eigengenes for each subtype of cells instead of average expression values of each module?

### ISSUE THREAD

**Issue by kaanokay** [smorabit/scWGCNA#2]
Hi @smorabit,

First of all, I'd like to thank you for this nice pipeline.

I'm wondering about what's the difference between module eigengenes and the average expression level of genes in a module, exactly? Why did you use module eigengenes instead of average gene expression in each module for each cell subtype? For each cell type, how should we interpret the bar plot of module eigengenes? If someone wants to make a bar plot of module eigengenes, should they calculate the average of module eigengenes for each module in cell types?

Thank you for your interest.
Best regards.

**Comment by smorabit** [comment]
Hi there,

For clarification, the module eigengene is a metric that summarizes the gene expression signature for the entire module by taking the subset of the whole expression matrix that contains only the genes for a given module, then performing principal component analysis on that subset matrix, and returning just the first principal component as the "module eigengene". This is a very commonly used output from WGCNA to represent gene expresison of an entire module, since the first principal component should capture a decent amount of the variance attributed to the expression of genes in a given module. The average expression of all genes in a module might give a similar answer, but there would be a bias since some genes are expressed at much higher levels than others, while this bias would be diminished in the module eigengene calculation.

I would not suggest making a bar plot to show module eigengenes, because it would not show the variability of module eigengene values across cells / samples etc, therefore it is better to show a box-and-whisker plot or a violin plot of module eigenegenes. 

For interpretation, let's say you have one module that has a significantly higher eigengene in condition X compared to condition Y. You might then infer that your module has some association with condition X. If condition X is a drug treatment, you might infer that your module is a drug-responsive module, while other gene modules that don't have a significant difference between conditions X & Y would be drug-resilient modules.

**Comment by kaanokay** [comment]
Hi,

Thank you so much for very nice clarification. I'm more sure to make and decide something now upon your explanation.

Bw.
