### ISSUE TITLE
co-expression network analysis on more than one  cluster simultaneously

### ISSUE THREAD

**Issue by naiem-99** [smorabit/scWGCNA#207]
Hello Sam, Hope you are doing well.

I have some questions regarding hdWGCNA as part of my project works overlaps this. Based on their score, I want to find module and hub genes in malignant cells(Endothelial), which were divided into two clusters (C1, C2). Now, is it wise to find module genes/ hub genes in whole single cells Seurat object and correlate them with score(trait)  or find individuals cluster module genes/ hub genes and correlate them with score? If so, how can I conduct two cluster co-expression network analyses simultaneously? 
in command. seurat_obj <- SetDatExpr(
  seurat_obj,
  group_name = c("INH", "EX"),
  group.by='cell_type'
)
just  By putting two cluster names in the group.name will  calculate two co-expression networks in further commands?

**Comment by smorabit** [comment]
Hi,

When you say "simultaneously", are you asking about parallel processing? Currently you would have to run the networks one after the other. If you want to run them simultaneously, you can submit them as separate jobs if you have access to a compute cluster. 

You can either run the network for both clusters together, or compute separate networks for each cluster. These approaches will give different results and I cannot provide any meaningful advice about which would be better, since that is very dependent on your dataset. I would recommend trying it out both ways and comparing the results.

**Comment by smorabit** [comment]
Closing for now but please re-open if needed.

**Comment by naiem-99** [comment]
Thank you for your reply. Actually, I have tried both options, as you said, and selected a gene module that is highly expressed in one group in comparison to another.
