### ISSUE TITLE
Min sample size / biological replicate needed

### ISSUE THREAD

**Issue by klai001** [smorabit/scWGCNA#215]
Thanks for developing this really cool package! I'm super excited to try this out.
But before that, I want to know more about the dataset requirements for this analysis. Given how limited scran seq is in number of biological replicates, and that some of the cell types are only ~800 cells, I wanted to know if there's a minimum number of cell types and biological replicates needed to run this analysis. Ultimately the goal is to find differential module across conditions per corresponding cell type but that seems like a stretch to me- I only have 3 biological replicates per condition.

**Comment by smorabit** [comment]
Hi,

To clarify, we have not done any extensive or quantitative testing to determine the minimum number of cells or samples needed for hdWGCNA. In principle, since scRNA-seq produces thousands of cellular transcriptomic profiles from a single replicate, you only need one replicate to run hdWGCNA. For example, the isoform network analysis that we showed in [Fig. 4 of the hdWGCNA paper](https://www.cell.com/cell-reports-methods/pdf/S2667-2375(23)00127-3.pdf) only used one replicate.

I would not recommend running hdWGCNA unless you have a few thousand cells. It sounds like in your case the cell types that have ~800 cells would be too few. I believe that you could run hdWGCNA on this data, but I would be worried that the results would not be reproducible or meaningful. However, keep in mind that I have not done testing to determine this emperically, this is just based on my experience with running this pipeline on a bunch of datasets of different sizes.
