### ISSUE TITLE
Question about reproducing the vignette results

### ISSUE THREAD

**Issue by xyzheng123** [smorabit/scWGCNA#219]
**Reproducing the vignette results** 
Hi, 
Thank you for putting together this awesome package. I am currently experiencing some issues to reproduce the vignette results. From reading the “issues” page, I understand that you tend to not re-run the vignette after every point version update. But can you please update the vignette and if possible include session info for your set up, so I can ensure the appropriate versions of packages and dependencies were being installed. Can you also date the time when you lastly run the vignette? Thank you for your help!

**Comment by smorabit** [comment]
Hi,

Thank you for your suggestions. Indeed it has been a while since I have updated the vignette figures. I plan to update them in the next major update of hdWGCNA in a few weeks.

>  But can you please update the vignette and if possible include session info for your set up, so I can ensure the appropriate versions of packages and dependencies were being installed

I will also do this in the same update. Keep in mind that you do not need the exact versions that I have in order to run hdWGCNA.
