### ISSUE TITLE
what's the ModuleEigengenes() values meaning?

### ISSUE THREAD

**Issue by JackyCWH** [smorabit/scWGCNA#22]
Hi, I am so appreciated you developed this package, and I want to use it to analyze the scRNA-seq data in my thesis.

I have a little confused about the function 'ModuleEigengenes()' values meaning (see the figure below).
![image](https://user-images.githubusercontent.com/106717483/173186246-7b2e6201-64ae-49a9-a767-895884ad3ce3.png)
The values were among 5x~-9, and I have no idea how to explain the meaning of the values.
My goal is drawing a boxplot to compare with Module Eigengenes in different kinds of groups (ctrl vs. sample).

BTW, I also saw paper you published and the others,  Module Eigengenes were almost among in 1~-1, did I make something wrong?
Thanks so much for your help!

Best regards,

Jacky

**Comment by smorabit** [comment]
Hi Jacky, I appreciate your interest in hdWGCNA.

From the basics [tutorial page](https://smorabit.github.io/hdWGCNA/articles/basic_tutorial.html):

> Module Eigengenes (MEs) are a commonly used metric to summarize the gene expression profile of an entire co-expression module. Briefly, module eigengenes are computed by performing principal component analysis (PCA) on the subset of the gene expression matrix comprising each module. The first PC of each of these PCA matrices are the MEs.

Additionally I added a suggested reading section to the homepage of the hdWGCNA website with some links to papers describing the WGCNA methodology in depth. Honestly, if you are unfamiliar with the term module eigengene I think it is definitely worth reading at least the main [WGCNA paper ](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-9-559) since it is a critical concept for this analysis.

To answer the last part of your question

> BTW, I also saw paper you published and the others, Module Eigengenes were almost among in 1~-1, did I make something wrong?

Good question but I don't think that you did anything wrong. The range of the values depends on the specific algorithm used for PCA. In my original paper we used a different algorithm than we are using now, so the range of values are much lower. Now we use [irlba](https://cran.r-project.org/web/packages/irlba/irlba.pdf) which is better suited towards high dimensional datasets.
