### ISSUE TITLE
Question about module overlap with SFARI genes

### ISSUE THREAD

**Issue by ashleshagogate** [smorabit/scWGCNA#226]
Hi Sam,
How did you do the module overlap with SFARI genes analysis in figure 5 of your Cell Reports Methods paper? I was trying something similar to the Marker gene overlap analysis section in the Enrichment analysis vignette but it requires the specific DEG output dataframe. I just have the list of SFARI genes.
Thanks!
-Ashlesha

**Comment by smorabit** [comment]
Hi Ashlesha,

This is something that was done using custom code rather than hdWGCNA functions. I think it would be interesting to add a function into hdWGCNA to do gene overlap analysis with a custom list, but for now this is not possible in hdWGCNA directly. You can refer to the GitHub repository for the hdWGCNA paper to see how we did the overlap analysis with the SFARI genes.

To see how we did this please navigate to [this script](https://github.com/smorabit/hdWGCNA_paper/blob/main/Figure5/Figure5.Rmd) and scroll down to the code block starting at line number 332.
