### ISSUE TITLE
pbmc <- ModuleEigengenes(   pbmc,   group.by.vars = "Sample" ） # Error in !CheckWGCNAName(seurat_obj, wgcna_name) : invalid argument type

### ISSUE THREAD

**Issue by Baozi9** [smorabit/scWGCNA#234]
Hi，When I run this line of code, there is an error, may I ask what is the problem? My Seutrat R package is 4.4 and hdWGCNA is 0.3.0. Is there a conflict between the two? If there is a conflict how to install the previous version of hdWGCNA?

**Comment by drake77777** [comment]
Maybe you can just reinstall the hdWGCNA package, i ran into this error too, and i reinstalled the package as following code : devtools::install_github('smorabit/hdWGCNA', ref='dev'), problem solved! And i got seurat v4 and v5 both in different path, so it's probably not because the version of seurat.

**Comment by smorabit** [comment]
Closing because this is a duplicate issue, please see issue #233

**Comment by Baozi9** [comment]
> Maybe you can just reinstall the hdWGCNA package, i ran into this error too, and i reinstalled the package as following code : devtools::install_github('smorabit/hdWGCNA', ref='dev'), problem solved! And i got seurat v4 and v5 both in different path, so it's probably not because the version of seurat.

Thanks a lot! I"ll try it again!
