### ISSUE TITLE
Does ModuleEigengenes based off of HVGs or co-expression module

### ISSUE THREAD

**Issue by Paria06** [smorabit/scWGCNA#269]
Dear @smorabit 
I am trying to subset my dataset to perform hdWGCNA and am unsure whether I need to recalculate highly variable genes (HVGs). According to the tutorial, the ModuleEigengenes function summarizes the co-expression module, which suggests that the genes assigned to each module are the input.

First, I would like to understand how HVGs are incorporated into this analysis and how ModuleEigengenes are computed across the entire dataset (comparing the cell type of interest to other cell types).

Second, if HVGs are required, should I recalculate them in the subsetted dataset? If so, how should I proceed?

Third, when performing the analysis as in #265, the ModuleFeaturePlot results appear odd:

<img width="801" alt="Screenshot 2024-05-30 at 09 20 45" src="https://github.com/smorabit/hdWGCNA/assets/52675953/4bf46276-49c2-4030-a468-fc49abbc3ad6">

As seen in the feature plot, the OPC1 sub-cluster is not highlighted for roughly half of the modules. I am unsure why this discrepancy occurs and whether it is related to the HVGs.

I would greatly appreciate your input on these matters.

Thank you,
Paria

**Comment by smorabit** [comment]
Hi Paria,

> First, I would like to understand how HVGs are incorporated into this analysis and how ModuleEigengenes are computed across the entire dataset (comparing the cell type of interest to other cell types).

To clarify, HVGs are not used to calculate module eigengenes.

> As seen in the feature plot, the OPC1 sub-cluster is not highlighted for roughly half of the modules. I am unsure why this discrepancy occurs and whether it is related to the HVGs.

You are performing network analysis specifically in OPC1, or am I mistaken? If that is the case, here it seems that you are seeing some modules that are not really expressed or are lowly expressed in OPC1, and they are expressed in other cell types. This commonly occurs with hdWGCNA and I can try to briefly explain some reasons why. It doesn't have to do with HVGs, but it does have to do with the genes that you use as input to hdWGCNA. Based on the tutorial, we suggest using genes that are expressed in 5% of cells.

```
seurat_obj <- SetupForWGCNA(
  seurat_obj,
  gene_select = "fraction", # the gene selection approach
  fraction = 0.05, # fraction of cells that a gene needs to be expressed in order to be included
  wgcna_name = "tutorial" # the name of the hdWGCNA experiment
)
```

Your target cell cluster (OPC1) might lowly express some of these genes that are expressed higher in other cell types. Even if these genes are lowly expressed by OPC1, they could still form a co-expression module. Since Module Eigengenes are based on principal components, the resulting ME values are relative to the data that is present. In this case you identified the modules in OPC1 only, but you used the whole dataset to compute MEs, and it is possible that the ME values could be much higher in some other cell types compared to OPC1 for some of the modules, because the genes in that module are higher expressed in those other cell types.

**Comment by Paria06** [comment]
Thanks a lot for the clarification!
> You are performing network analysis specifically in OPC1, or am I mistaken? If that is the case, here it seems that you are seeing some modules that are not really expressed or are lowly expressed in OPC1, and they are expressed in other cell types. This commonly occurs with hdWGCNA and I can try to briefly explain some reasons why. It doesn't have to do with HVGs, but it does have to do with the genes that you use as input to hdWGCNA. Based on the tutorial, we suggest using genes that are expressed in 5% of cells.

Yes, I do. And ModuleEigengenes was done in an entire dataset. Also I am using genes that are expressed in 5% of cells.

I was wondering if you have any advice to get fewer modules but more specific ones.
Thanks,
Paria

**Comment by smorabit** [comment]
> I was wondering if you have any advice to get fewer modules but more specific ones

I think it is best for organisational purposes to keep one GitHub issue to a single topic, or very closely related topics, so please open a new issue to ask this question.
