### ISSUE TITLE
 Compatibility of hdWGCNA with Visium HD Data

### ISSUE THREAD

**Issue by wnddl111** [smorabit/scWGCNA#286]
Hello,

I am interested in using the hdWGCNA package with Visium HD data. Firstly, I would like to confirm if this is possible.

While attempting to proceed on my own, I encountered an issue due to the absence of the required metadata in my dataframe. Specifically, the package requires 'row', 'col', 'imagerow', and 'imagecol' columns.

Could you please clarify what is meant by the 'row' and 'col' columns in this context?

Regarding 'imagerow' and 'imagecol', I am considering using the 'x.coordinates' and 'y.coordinates' obtained from the Loupe Browser export CSV. Would this approach be acceptable?

Your guidance on how to properly prepare my dataframe for hdWGCNA would be greatly appreciated.

Thank you for your assistance.

Best regards,
juyoung lee

**Comment by smorabit** [comment]
Hi,

I have not tested hdWGCNA with Visium HD, but I think it could work in theory. Since I have not tried it, I currently have no recommendation on how to handle Visium HD data.

To clarify, your issue is very similar to #278. It seems like when Visium HD was released, Seurat changed how their data structure handles the images and coordinates, making it incompatible with hdWGCNA. I am planning to fix this but I am currently busy with other obligations and I won't have time to fix it for a few weeks.

**Comment by reviewJ** [comment]
Facing the same issue with 10X Visium datasets.

**Comment by Akankxha** [comment]
Facing the same issue with the 10X Visium Dataset. Any updates or possible workarounds?

**Comment by smorabit** [comment]
Hi,

[Please see this tutorial for using Visium HD data.](https://smorabit.github.io/hdWGCNA/articles/ST_basics.html#x-visium-hd-dataset)
