### ISSUE TITLE
ModuleRadarPlot

### ISSUE THREAD

**Issue by joe-jhou2** [smorabit/scWGCNA#293]
I noticed ModuleRadarPlot has been added to new version 0.3.03. I've upgraded to the latest version, yet, ModuleRadarPlot not found. could you please recheck? thanks.

**Comment by yingyonghui** [comment]
+1

**Comment by smorabit** [comment]
Thank you for pointing this out. I just checked, the function could not be loaded because I forgot to generate the documentation file. I just added the document so it should work now (version number not changed). Please re-install hdWGCNA and try again. I tried it myself and now `ModuleRadarPlot` is working for me.

**Comment by xdzperfect** [comment]
hello! professor smorabit! I just install new version 0.4.05 of hdWGCNA, I once again get the same issue, error reprt "ModuleRadarPlot" function not found! I check the plotting.r file I find do not have ModuleRadarPlot  function! when I add it the R script and reRun it, I got new issuse " lazy-load database 'D:/software/exe/R-4.3.2/R-4.3.2/library/hdWGCNA/R/hdWGCNA.rdb' is corrupt" file is error! Could you help me? and  recheck? thanks
