### ISSUE TITLE
Is it possible to extract only the co-expressed genes of a gene?

### ISSUE THREAD

**Issue by levinhein** [smorabit/scWGCNA#30]
Hello. Is it possible to extract those genes that are only co-expressed with a specifie gene?

For example, in this coexpression network,  it appears that JUNB is co-expressed with a number of genes in this plot, but is not co-expressed with SORL1 and ITGB2 (please correct me if my interpretation is wrong and if there is a different interpretation). 

Thank you!

![image](https://user-images.githubusercontent.com/68268222/175284586-fc5e938f-f146-4aef-8977-e665fa6af691.png)

**Comment by smorabit** [comment]
The topological overlap matrix (TOM) is a square matrix that contains all of the co-expression information for each pair of genes. 

```
TOM <- GetTOM(seurat_obj)
```

If you used the recommended workflow for hdWGCNA, that means a soft threshold was applied, so there is a continuous range of values in the TOM rather than a 1/0 for co-expressed or not co-expressed.

For example let's say you want to identify the genes that are co-expressed with the gene SST. You can subset the TOM based on this gene, and then sort the topological overlap vector:

```

cur_gene <- 'SST'
cur_tov <- TOM[cur_gene,]

# sort the topological overap vec 
cur_tov <- cur_tov[rev(order(cur_tov))]

```

Let's say you want the 25 most co-expressed genes with SST:

```
head(cur_tov, 25)
```

I hope that this example is helpful. I am planning to put this and a few other things into a FAQ page soon.
