### ISSUE TITLE
cannot install hdWGCNA package in R

### ISSUE THREAD

**Issue by yulchen810** [smorabit/scWGCNA#308]
Hi, 
Thank you for your great work!
I followed your configuration and installation in conda and R.
I failed to install hdWGCNA in R(version 4.2.2), here is the  
**![image](https://github.com/user-attachments/assets/8bf0352a-a17e-4904-91bc-6875b3b4ae89)**
it says the URL is wrong, is there any solution? 

Thank you very much!

Best

**Comment by rootze** [comment]
@yulchen810 Thanks for using the hdWGCNA package. Your error is not due to hdWGCNA; instead, your IP address was rate-limited. Or at least that's what happened when I tried to duplicate your error; I installed some other packages from GitHub and CRAN and then failed to install the hdWGCNA package. But I was able to install the hdWGCNA package later (10-20 mins later after reactivating my R env). 
If this is not working for you, you can check the issue #302

**Comment by yulchen810** [comment]
Hi, Ze  I have downloaded hdWGCNA package from github and successfully installed it locally. Thank you very much.  Best,  Xiaoyan ---- Replied Message ---- From ***@***.***> Date 09/04/2024 07:27 To ***@***.***> Cc Xiaoyan ***@***.***>***@***.***> Subject Re: [smorabit/hdWGCNA] cannot install hdWGCNA package in R (Issue #308) @yulchen810 Thanks for using the hdWGCNA package. Your error is not due to hdWGCNA; instead, your IP address was rate-limited. Or at least that's what happened when I tried to duplicate your error; I installed some other packages from GitHub and CRAN and then failed to install the hdWGCNA package. But I was able to install the hdWGCNA package later (10-20 mins later after reactivating my R env). If this is not working for you, you can check the issue #302 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by yulchen810** [comment]
@rootze Hi, I have downloaded hdWGCNA package from github and successfully installed it locally. Thank you very much.
