### ISSUE TITLE
Implementation of SEACells?

### ISSUE THREAD

**Issue by cnk113** [smorabit/scWGCNA#31]
Hello,

This is a great package, I was wondering if the metacell construction was ever compared to recently released SEACells package? I've found SEACells to be pretty robust, and might be ideal to implement in hdWGCNA?

Thanks,
Chang

**Comment by smorabit** [comment]
Hi,

I appreciate the comment. I actually do have plans to compare the hdWGCNA metacells to SEACells. I actually tried this a while ago but could never get SEACells to install ... I just tried again and I still can't install it on my system. Regardless of the comparison, I don't have any plans to include SEACells as part of the hdWGCNA framework. Mostly because SEACells is a python package while I am trying to keep the hdWGCNA workflow entirely within R. Maybe things will change when if SEACells matures, but for the time being it doesn't seem like something I will include as a dependency.

**Comment by smorabit** [comment]
Hi again,

I have now included a new tutorial showing how to use SEACells with hdWGCNA. Seems like at least in this one dataset SEACells is a suitable approach to use with hdWGCNA. However, it is worth mentioning that I haven't been able to run SEACells on a large dataset so use it at your own risk!

https://smorabit.github.io/hdWGCNA/articles/other_metacells.html

**Comment by cnk113** [comment]
Thanks! Interesting results, it does look like SEACells give you more granular modules, would you say its a more expressive metacell method?

**Comment by smorabit** [comment]
In this particular dataset, we were indeed able to idenfity a few more modules using SEACells compared to hdWGCNA or MC2, but overall I think the results are comparable across the different methods. It is hard to say which is a "more expressive" metacell method without additional testing. There's also a matter of practicality, and I have been able to run the hdWGCNA metacell algorithm on datasets of ~1 million cells in under 2 hours, while I am not sure that SEACells is currently able to scale that high in any reasonable amount of time.

Overall  it looks like SEACells can definitely be used in place of the hdWGCNA metacell algorithm for co-expression network analysis!
