### ISSUE TITLE
MetaspotsByGroups: 'data' must be of a vector type, was 'NULL' 

### ISSUE THREAD

**Issue by Li-ZhiD** [smorabit/scWGCNA#314]
Hi, 

I run spatial data of stereo-seq data by using
`
stRNA@meta.data$row <- stRNA@meta.data$x
stRNA@meta.data$col <- stRNA@meta.data$y
stRNA@meta.data$imagerow <- stRNA@meta.data$x
stRNA@meta.data$imagecol <- stRNA@meta.data$y

stRNA <- SetupForWGCNA(
   stRNA,
   gene_select = "fraction",
   fraction = 0.05,
   wgcna_name = "STO"
)

stRNA <- MetaspotsByGroups(
   stRNA,
   group.by = c("Chip.ID"),
   ident.group = "Chip.ID",
   assay = 'RNA'
)
`
an error:
`
Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'
`

Could any one help me?

**Comment by smorabit** [comment]
Hi,

I have not tested hdWGCNA for stereoseq data. The function `MetaspotsByGroups` is specifically for Visium data, because it takes advantage of the spot layout in the Visium slides, which I believe is not similar for stereoseq. You might be able to use `MetacellsByGroups` instead.

**Comment by Li-ZhiD** [comment]
Thank you! Will be compatible with stereo-seq in the future?

**Comment by smorabit** [comment]
While I have not written a tutorial for stereo-seq, hdWGCNA should already be compatible with stereo-seq.

You should try to follow the tutorial for the [Curio Seeker](https://smorabit.github.io/hdWGCNA/articles/ST_basics.html#curio-seeker-dataset) or the [Visium HD](https://smorabit.github.io/hdWGCNA/articles/ST_basics.html#x-visium-hd-dataset) datasets, since it should be similar. 

Most importantly, you want to run `MetacellsByGroups` using the spatial coordinates instead of a dimensionality reduction. [You can see in this tutorial](https://smorabit.github.io/hdWGCNA/articles/ST_basics.html#construct-metacells-with-metacellsbygroups-1), we create a new DimReducObject in the Seurat object to store the spatial coordinates, and then we are able to run `MetacellsByGroups`. In principle, you should be able to adapt this code for a stereo-seq dataset.

**Comment by Li-ZhiD** [comment]
Thank you!
