### ISSUE TITLE
ModuleEigengenes throws “Error in intI(i, n = x@Dim[1], dn[[1]],..."

### ISSUE THREAD

**Issue by Dimmiso** [smorabit/scWGCNA#34]
Hi, 
Thanks a lot for nice package! I look forward to use it for my data!
Please, see under link(https://drive.google.com/drive/folders/1kiL1PhsL-a8fHHn0ijMouzX_ZtzTv9Ze?usp=sharing)
a code and workspace with a Seurat object. 

Attempts to run this code on provided objects end up with error on ModuleEigengenes (its any provided variant): “Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) :   no 'dimnames[[.]]': cannot use character indexing”
I tried also the same code on different Seurat object but it gave the same error outcome. 
What I do wrong? 

Another minor thing: 
When I run MetacellsByGroups either without specifying assay & slot or with (assay = 'integrated',  slot = 'scale.data') the resulting seurat object contains an object with identical name, "RNA", in the slot (seurat_obj.1@misc[["tutorial"]][["wgcna_metacell_obj"]]@assays), but based on its dimensions one can conclude that if MetacellsByGroups was run with (assay = 'integrated',  slot = 'scale.data') this output object, "RNA", is built indeed on integrated data, while still have name “RNA” and internal slot “counts”. Probably, this has the following effect: when I run next command in the flow, SetDatExpr, without explicit specifying assay = 'RNA', the command throws:

“Error in SetDatExpr(seurat_obj.1, group_name = names(table(seurat_obj.1$clust.H)),  : 
  Assay not found. Check names(seurat_obj@assays) or names(GetMetacellObject(seurat_obj)@assays)
In addition: Warning message: In SetDatExpr(seurat_obj.1, group_name = names(table(seurat_obj.1$clust.H)),  : assay not specified, trying to use assay integrated”

But when I explicitly specify (assay = 'RNA') the command works well. Should it be like that? 

Thanks a lot for your help!
Dmitry

**Comment by smorabit** [comment]
Hi Dmitry, I appreciate sending your data and your code, that made it a lot easier to figure out what your issue was!

Happy to say that I was able to find the source of your issue. The `ModuleEigengenes` function was looking for a counts matrix in the Seurat object (even though the function didn't actually use the counts matrix...), but your `integrated` assay didn't have a counts matrix, therefore an error was thrown. I updated the function so it no longer requres a counts matrix for this function, only a normalized data matrix, and it should give a more informative error message if the normalied data matrix is missing.

I also fixed your other issue, so when you run `MetacellsByGroups`, the name of the assay provided will carry over to the metacell object.

Here's the modified version of your code which I was able to successfully run. Note that at the top of the script the most recent version of hdWGCNA is installed, which includes these bugfixes.

```



# load R packages
library(Seurat)
library(tidyverse)
library(patchwork)
library(cowplot)
library(Matrix)
library(WGCNA)
library(SeuratWrappers)
library(harmony)
theme_set(theme_cowplot())

# re-install hdWGCNA
devtools::install_github('smorabit/hdWGCNA', ref='dev')
library(hdWGCNA)


source('/dfs7/swaruplab/smorabit/analysis/scWGCNA/bin/spatial_functions.R')
source("/pub/smorabit/hdWGCNA/bin/spatial_functions.R")
setwd('/dfs7/swaruplab/smorabit/analysis/scWGCNA/issues/071922/')

# load dataset
load('data/WGCNA_10x_to_GitHub.rdata')

seurat_obj <- SetupForWGCNA(
  seurat_obj,
  gene_select = "variable", # the gene selection approach
  wgcna_name = "tutorial" # the name of the hdWGCNA experiment
)


# construct metacells  in each group
seurat_obj <- MetacellsByGroups(
  seurat_obj = seurat_obj,
  group.by = c("clust.H", 'plate'), # specify the columns in seurat_obj@meta.data to group by
  ident.group = 'clust.H', # set the Idents of the metacell seurat object
  k = 10, # nearest-neighbors parameter
  max_shared = 5, # maximum number of shared cells between two metacells
  min_cells = 25, #default = 100
  assay = 'integrated',
  slot = 'data',
  verbose = FALSE
)

seurat_obj <- SetDatExpr(
  seurat_obj,
  group_name = names(table(seurat_obj$clust.H)), # the name of the group of interest in the group.by column
  group.by='clust.H' # the metadata column containing the cell type info. This same column should have also been used in MetacellsByGroups
)


seurat_obj <- TestSoftPowers(
  seurat_obj,
  setDatExpr = FALSE, # set this to FALSE since we did this above
)


seurat_obj <- ConstructNetwork(
  seurat_obj, soft_power=8,
  overwrite_tom = T,
  setDatExpr=F,
  verbose = T
)

pdf("dendro.pdf",height=3, width=6)
PlotDendrogram(seurat_obj, main='hdWGCNA Dendrogram')
dev.off()


# compute all MEs in the full single-cell dataset
seurat_obj <- ModuleEigengenes(
  seurat_obj,
  group.by.vars = 'plate',
  verbose = F,
  wgcna_name = 'tutorial',
  assay = 'integrated'
)


plot_list <- ModuleFeaturePlot(seurat_obj,  order=TRUE, alpha=1, restrict_range=FALSE,)
pdf("featureplot_MEs.pdf",height=6, width=9)
wrap_plots(plot_list, ncol=4)
dev.off()


```

Please let me know if this solves your problem. 

Just as a word of advice, in your code you are only using 1,000 genes for network analysis. I checked the dendrogram and the module eigengenes, and I think the results look fine , but you may want to expand to a larger list of genes.

![Screen Shot 2022-07-20 at 12 15 29 PM](https://user-images.githubusercontent.com/20936230/180063849-f24bbbe9-e943-4e51-8075-06db25c52332.png)

![Screen Shot 2022-07-20 at 12 15 51 PM](https://user-images.githubusercontent.com/20936230/180063898-f43c2d7a-1921-45bd-b708-3866d75f2ada.png)

**Comment by Dimmiso** [comment]
Hellow, Smorabit, 
Thanks a lot for quick localizing and fixing issues! It is very kind of you! I will continue with your package as soon as I am back from vacation! Best, Dmitry
