### ISSUE TITLE
Module projection works one direction but not the other

### ISSUE THREAD

**Issue by Dimmiso** [smorabit/scWGCNA#43]
Hi, 

Thanks a lot for great package!
 
I need to project modules from seurat_obj.NTW to seurat_obj.hs.10x, but it does not work. However it works opposite direction, from hs.10x to .NTW object (link to my R enveroment is here:
https://drive.google.com/drive/folders/1BUMuRJZZzbdWt4ExANNK6oaUKY7nZtOT?usp=sharing)

 seurat_query <- ProjectModules(
  seurat_obj = seurat_obj.hs.10x,
  seurat_ref = seurat_obj.NTW,
  scale_genes = T,
  wgcna_name_proj="Sh_projected", # name of the new hdWGCNA experiment in the query dataset
  wgcna_name = "tutorial" # name of the hdWGCNA experiment in the ref dataset
)

seurat_query <- ProjectModules(
  seurat_obj = seurat_obj.NTW,
  seurat_ref = seurat_obj.hs.10x,
  scale_genes = T,
  wgcna_name_proj="Sh_projected", # name of the new hdWGCNA experiment in the query dataset
  wgcna_name = "tutorial" # name of the hdWGCNA experiment in the ref dataset
)

A error thrown in very beginning of the first command is:
[1] "n genes:"
[1] 0
NULL
Error in gene_name %in% genes_use : object 'gene_name' not found

I suspect something is wrong with seurat_obj.NTW object. Can you, please, help to find what is the issue? 
Thanks a lot!

**Comment by Dimmiso** [comment]
Hi
I managed to push it a bit further. If one explicitly runs:
modules.1 <- GetModules(seurat_obj.NTW) 

and then us modules.1 as parameter "module":

seurat_query <- ProjectModules(
seurat_obj = seurat_obj.hs.10x,
seurat_ref = seurat_obj.NTW,
modules = modules.1,
scale_genes = T,
wgcna_name_proj="Sh_projected", # name of the new hdWGCNA experiment in the query dataset
wgcna_name = "tutorial" # name of the hdWGCNA experiment in the ref dataset
)
ProjectModules starts runnig properly, but then through a error in the middle: 
"Error in CreateAssayObject(counts = counts, min.cells = min.cells, min.features = min.features,  : 
 No cell names (colnames) names present in the input matrix"


Thanks!
Dmitry

**Comment by smorabit** [comment]
Hi Dmitry,

I think that I found the root of your issue. `seurat_obj.hs.10x` has only 1000 genes while `seurat_obj.NTW` has ~13k genes. This means that many of the genes assigned to co-expression modules in `seurat_obj.NTW` were completely missing from `seurat_obj.hs.10x`, so when you try to project the modules from `seurat_obj.NTW` to `seurat_obj.hs.10x`, several of the modules had very few or zero genes that were present in `seurat_obj.hs.10x`.

Based on your issue I updated `ProjectModules` to exclude modules with too many missing genes. By default, 50% of the genes must be present or else the module is excluded, but this can be changed with the `overlap_proportion` parameter. In your case, only a single module meets this criteria.

Ultimately it won't be possible to project the modules from `seurat_obj.NTW` to `seurat_obj.hs.10x` and get any meaningful results because there are simply too many genes missing.

**Comment by Dimmiso** [comment]
Hi Sam, 
thank you very much for helping with this! It makes perfect sense! And it works now: as long as one understand the reasone, one can almost always find the way around the problem: I simply cluster now seurat_obj.NTW only using genes which exist in seurat_obj.hs.10x (and this clustering makes perfect sense) and then do module projection. Thanks a lot for support!
