### ISSUE TITLE
Interpretation of negative kME genes

### ISSUE THREAD

**Issue by meaksu** [smorabit/scWGCNA#75]
Hi,
I was wondering how to interpret some genes having a negative kME value for their respective modules like Module 8 in the following plot. Does this mean these genes are negatively correlated with this module?

![Layer2_All_Samples_kME_ranking](https://user-images.githubusercontent.com/71838948/208323528-f09793e2-50e8-451c-94e8-66d3bbf48ba5.png)

Also, as a separate question I was wondering whether it is valid to use the Metacells function rather than Metaspots for spatial data. I have many samples and am not interested in the spatial visualization with this particular package, but rather grouping spots transcriptionally and treating the data almost like single cell data. Would this be allowed?

Thanks!

**Comment by smorabit** [comment]
In general we compute the co-expression network with the metacell expression matrix, but we actually compute the kME values using the single-cell expression matrix. This discrepancy can lead to negative kME values showing up occasionally. In a future update I am going to allow for re-assignment of genes with negative kME values to the module that has the highest kME value, or to the grey module. 


I think that you should be able to use the Metacells function instead of Metaspots for spatial data if you choose to do so.
