### ISSUE TITLE
The questions of soft power thresholds and sample size.

### ISSUE THREAD

**Issue by maqingyue** [smorabit/scWGCNA#86]
Hi,
when I analyze my data and select the soft threshold, the figure is like this. Why does the following value fluctuate so much? Is this normal?

[soft-power-thresholds.pdf](https://github.com/smorabit/hdWGCNA/files/10778962/soft-power-thresholds.pdf)

Besides，my data is the spatial transcriptome integration data of three young mice and three old mice, I don't know whether so many samples are enough for hdWGCNA.

Finally, there is only one tutorial related to the space transcriptome, and the other tutorials of hdWGCNA use the data of Zhou et al. 2020 study. Do these tutorials apply to the space transcriptome data?

I'm looking forward to your reply, thank you！

**Comment by smorabit** [comment]
Hi,

>  when I analyze my data and select the soft threshold, the figure is like this. Why does the following value fluctuate so much? Is this normal?

I am not sure why your soft power values are fluctuating. If you can provide more information about dataset and what code you used, it would help me to figure it out. Since your results show that there are several `soft_power` values that reach a scale-free topology fit  >= 0.8, I don't think you need to worry about the fluctuating values, unless the downstream results look abnormal as well.

> Besides，my data is the spatial transcriptome integration data of three young mice and three old mice, I don't know whether so many samples are enough for hdWGCNA.

This is enough samples for hdWGCNA, you can run hdWGCNA with only one sample if you wanted to.

> Finally, there is only one tutorial related to the space transcriptome, and the other tutorials of hdWGCNA use the data of Zhou et al. 2020 study. Do these tutorials apply to the space transcriptome data?

Yes these tutorials also apply to spatial transcriptomics data.

In the future when you have more than one unrelated question, please open them as separate issues for better organization.

**Comment by maqingyue** [comment]
Thanks for your answer, and different questions will be asked separately in the future.
