### ISSUE TITLE
ModuleTraitCorrelation error 

### ISSUE THREAD

**Issue by Bioinformatics-rookie** [smorabit/scWGCNA#94]
**Describe the bug**
when I run ModuleTraitCorrelation , list an error here 
Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'

**Steps to reproduce**

```
seurat_obj <- ModuleTraitCorrelation(
  seurat_obj,
  traits = cur_traits,
  group.by='metacell_grouping'
)

```

**R session info**
Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'

**Comment by smorabit** [comment]
What are you using for `cur_traits`?

**Comment by Bioinformatics-rookie** [comment]
nCount_RNA' and  'nFeature_RNA'

**Comment by smorabit** [comment]
Are you able to reproduce the error on the tutorial dataset or another publicly available dataset?

**Comment by Bioinformatics-rookie** [comment]
When I use  tutorial dataset，It runs successfully，But with my own data it doesn't work，It may be a problem with my data, and I will take a closer look

**Comment by Stray357** [comment]
Hi, I'm sorry to reopen the question. I reproduced the exact same error with the tutorial dataset, the dendrogram is fine, however, ModuleTraitCorrelation doesn't work

Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  :
  'data' must be of a vector type, was 'NULL'
Calls: ModuleTraitCorrelation ... as.matrix -> <Anonymous> -> as.matrix.default -> array

The code I use is the same as in the tutorial
`library(Seurat)
library(tidyverse)
library(cowplot)
library(patchwork)
library(WGCNA)
library(hdWGCNA)

set.seed(12345)
theme_set(theme_cowplot())

DIR = <directory_to_data>
seurat_obj <- readRDS(paste0(DIR,'Zhou_2020_control.rds'))


seurat_obj <- SetupForWGCNA(
  seurat_obj,
  gene_select = "fraction", # the gene selection approach
  fraction = 0.05, # fraction of cells that a gene needs to be expressed in order to be included
  wgcna_name = "tutorial" # the name of the hdWGCNA experiment
)

seurat_obj <- MetacellsByGroups(
  seurat_obj = seurat_obj,
  group.by = c("cell_type", "Sample"), # specify the columns in seurat_obj@meta.data to group by
  reduction = 'harmony', # select the dimensionality reduction to perform KNN on
  k = 25, # nearest-neighbors parameter
  max_shared = 10, # maximum number of shared cells between two metacells
  ident.group = 'cell_type' # set the Idents of the metacell seurat object
)

seurat_obj <- NormalizeMetacells(seurat_obj)


seurat_obj <- SetDatExpr(
  seurat_obj,
  group_name = "INH", # the name of the group of interest in the group.by column
  group.by='cell_type', # the metadata column containing the cell type info. This same column should have also been used in MetacellsByGroups
  assay = 'RNA', # using RNA assay
  slot = 'data' # using normalized data
)

seurat_obj <- TestSoftPowers(
  seurat_obj,
  networkType = 'signed' # you can also use "unsigned" or "signed hybrid"
)

seurat_obj <- ConstructNetwork(
  seurat_obj,
  tom_name = 'INH', # name of the topoligical overlap matrix written to disk
  overwrite_tom = TRUE
)

#to module-trait correlation
# convert sex to factor
seurat_obj$msex <- as.factor(seurat_obj$msex)

# convert age_death to numeric
seurat_obj$age_death <- as.numeric(seurat_obj$age_death)

# list of traits to correlate
cur_traits <- c('braaksc', 'pmi', 'msex', 'doublet_scores', 'age_death','nCount_RNA', 'nFeature_RNA', 'total_counts_mt')



seurat_obj <- ModuleTraitCorrelation(
  seurat_obj,
  traits = cur_traits,
  group.by='cell_type'
)

mt_cor <- GetModuleTraitCorrelation(seurat_obj)
`
The wget command is not working in toturial so I got the dataset from the GoogleDrive link.
https://drive.google.com/drive/folders/1yxolklYrwFB9Snwr2Dp_W2eunBxaol4A

session_info:
![image](https://github.com/user-attachments/assets/2b13a4b4-0ee7-4c8d-acd1-2dd14e3e146b)
![image](https://github.com/user-attachments/assets/87d67b0e-bea9-465e-a3d5-fd08f4c9941d)
